# PROXY代理配置
ip-proxy:
  # 代理池配置
  # 最大活动数
  maxActive: 200
  # 最大空闲数
  maxIdle: 20
  # 最大等待时间
  maxWait: 100
  #返回是否校验
  testOnReturn: false
  #借出是否校验
  testOnBorrow: true
  #是否后进先出
  lifo: false
  #提前多少分钟销毁对象
  testTime: 3
  #设定间隔每过多少毫秒进行一次后台对象清理的行动。如果这个值不是正数，则实际上不会进行后台对象清理。
  timeBetweenEvictionRunsMillis: -1000
  #设定在进行后台对象清理时，是否还对没有过期的池内对象进行有效性检查。不能通过有效性检查的对象也将被回收。
  testWhileIdle: true
  #设定在进行后台对象清理时，每次检查几个对象。如果这个值不是正数，则每次检查的对象数是检查时池内对象的总数乘以这个值的负倒数再向上取整的结果――也就是说，
  #如果这个值是-2（-3、-4、-5……）的话，那么每次大约检查当时池内对象总数的1/2（1/3、1/4、1/5……）左右。
  numTestsPerEvictionRun: 3
  # 获取ip 方式 0 为免费 1 为付费 2 为免费和付费同时进行
  iPType: 2
  # IP代理请求路径
  httpPath: "http://webapi.http.zhimacangku.com/getip"
  # IP代理请求参数
  httpProxy:
    num: "1"
    type: "2"
    pro: ""
    city: ""
    yys: "0"
    port: "1"
    pack: "51524"
    amount: "1"
    ts: "1"
    ys: "1"
    cs: "1"
    lb: "1"
    sb: "0"
    pb: "4"
    mr: "1"
    regions: ""